//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.23 at 03:04:02 PM MSK 
//


package ru.yusdm.javacore.lesson14serialization.homework.jaxb.generatedclasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.yusdm.javacore.lesson14serialization.homework.jaxb.generatedclasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.yusdm.javacore.lesson14serialization.homework.jaxb.generatedclasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InitData }
     * 
     */
    public InitData createInitData() {
        return new InitData();
    }

    /**
     * Create an instance of {@link Mark }
     * 
     */
    public Mark createMark() {
        return new Mark();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link InitData.Marks }
     * 
     */
    public InitData.Marks createInitDataMarks() {
        return new InitData.Marks();
    }

    /**
     * Create an instance of {@link Mark.Models }
     * 
     */
    public Mark.Models createMarkModels() {
        return new Mark.Models();
    }

}
